version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "/packages/nekoton_bridge/rust"
    schedule:
      interval: daily
