export declare enum RpcErrorCode {
    INTERNAL = 0,
    TRY_AGAIN_LATER = 1,
    INVALID_REQUEST = 2,
    RESOURCE_UNAVAILABLE = 3,
    METHOD_NOT_FOUND = 4,
    INSUFFICIENT_PERMISSIONS = 5,
    REJECTED_BY_USER = 6,
    CONNECTION_IS_NOT_INITIALIZED = 7,
    MESSAGE_EXPIRED = 8
}
