[package]
name = "nekoton_bridge"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.63.*"

[dependencies]
flutter_rust_bridge = "1.61.*"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
simplelog = "0.12.0"
log = { version = "0.4.17", features = ["kv_unstable"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.12.0"

