[package]
name = "nekoton_bridge"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.65.*"

[dependencies]
flutter_rust_bridge = "1.65.*"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
simplelog = "0.12.0"
log = { version = "0.4.17", features = ["kv_unstable"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
nekoton = { git = "https://github.com/broxus/nekoton.git", features = [
    "gql_transport",
    "jrpc_transport",
] }
nekoton-abi = { git = "https://github.com/broxus/nekoton.git" }
nekoton-utils = { git = "https://github.com/broxus/nekoton.git" }

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.0"

