// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.68.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

part 'bridge_generated.freezed.dart';

abstract class NekotonBridge {
  /// Test func
  Future<MnemonicType> resendMnemonic(
      {required MnemonicType mnemonic, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kResendMnemonicConstMeta;

  ///----------------------------
  /// CONTENT OF src/nekoton_wrapper/crypto/mnemonic/mnemonic_api.rs
  ///----------------------------
  /// Generate seed phrase by specified mnemonic type
  Future<GeneratedKeyG> ntGenerateKey(
      {required MnemonicType accountType, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNtGenerateKeyConstMeta;

  /// Get hints for input part of word of seed phrase to get possible words
  /// input: acco
  /// returns [account, accommodate, ...]
  Future<List<String>> ntGetHints({required String input, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNtGetHintsConstMeta;

  /// Generate public and secret keys from seed phrase and mnemonic type
  /// Returns json {'public': '...', 'secret': '...'}
  Future<String> ntDeriveFromPhrase(
      {required String phrase,
      required MnemonicType mnemonicType,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNtDeriveFromPhraseConstMeta;

  ///----------------------------
  /// CONTENT OF src/utils/api.rs
  ///----------------------------
  /// Init utils
  Future<void> initLogger(
      {required LogLevel level, required bool mobileLogger, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitLoggerConstMeta;

  /// Create log stream
  Stream<LogEntry> createLogStream({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateLogStreamConstMeta;

  /// Init caller
  Stream<DartCallStubRegistred> initCaller({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitCallerConstMeta;

  /// Callback functions for returning Dart method result
  Future<void> callSendResult(
      {required String id, required DynamicValue value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCallSendResultConstMeta;

  Future<void> simpleLog({required String string, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSimpleLogConstMeta;

  Future<void> simplePanic({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSimplePanicConstMeta;

  int simpleAdderSync({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSimpleAdderSyncConstMeta;

  Future<int> simpleAdder({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSimpleAdderConstMeta;

  Future<DynamicValue> stubDv({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStubDvConstMeta;

  Future<DartCallStub> stubDcs({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStubDcsConstMeta;

  Future<void> simpleCallDart({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSimpleCallDartConstMeta;

  Future<void> stubCallDart({required DartCallStub stub, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStubCallDartConstMeta;

  Future<void> simpleCallFunc0({required bool needResult, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSimpleCallFunc0ConstMeta;

  Future<void> simpleCallFunc1({required bool needResult, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSimpleCallFunc1ConstMeta;

  Future<void> simpleCallFunc2({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSimpleCallFunc2ConstMeta;

  Future<MyClass> newStaticMethodMyClass({required int a, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNewStaticMethodMyClassConstMeta;

  Future<String> myFormatMethodMyClass({required MyClass that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMyFormatMethodMyClassConstMeta;
}

class DartCallStub {
  final String fnName;
  final List<DynamicValue> args;
  final List<DynamicNamedValue> namedArgs;

  const DartCallStub({
    required this.fnName,
    required this.args,
    required this.namedArgs,
  });
}

class DartCallStubRegistred {
  final String? id;
  final DartCallStub stub;

  const DartCallStubRegistred({
    this.id,
    required this.stub,
  });
}

class DynamicNamedValue {
  final String name;
  final DynamicValue? value;

  const DynamicNamedValue({
    required this.name,
    this.value,
  });
}

@freezed
class DynamicValue with _$DynamicValue {
  const factory DynamicValue.u32(
    int field0,
  ) = DynamicValue_U32;
  const factory DynamicValue.i32(
    int field0,
  ) = DynamicValue_I32;
  const factory DynamicValue.u64(
    int field0,
  ) = DynamicValue_U64;
  const factory DynamicValue.i64(
    int field0,
  ) = DynamicValue_I64;
  const factory DynamicValue.f32(
    double field0,
  ) = DynamicValue_F32;
  const factory DynamicValue.f64(
    double field0,
  ) = DynamicValue_F64;
  const factory DynamicValue.string(
    String field0,
  ) = DynamicValue_String;
  const factory DynamicValue.megaStruct(
    String field0,
  ) = DynamicValue_MegaStruct;
  const factory DynamicValue.none() = DynamicValue_None;
}

/// Wrapper struct above GeneratedKey with suitable type for generation
class GeneratedKeyG {
  final List<String> words;
  final MnemonicType accountType;

  const GeneratedKeyG({
    required this.words,
    required this.accountType,
  });
}

/// Log entry
class LogEntry {
  final int timeMillis;
  final LogLevel level;
  final String tag;
  final String msg;

  const LogEntry({
    required this.timeMillis,
    required this.level,
    required this.tag,
    required this.msg,
  });
}

enum LogLevel {
  Trace,
  Debug,
  Info,
  Warn,
  Error,
}

@freezed
class MnemonicType with _$MnemonicType {
  const factory MnemonicType.legacy() = MnemonicType_Legacy;
  const factory MnemonicType.labs(
    int field0,
  ) = MnemonicType_Labs;
}

class MyClass {
  final NekotonBridge bridge;
  final int val;

  const MyClass({
    required this.bridge,
    required this.val,
  });

  static Future<MyClass> newMyClass(
          {required NekotonBridge bridge, required int a, dynamic hint}) =>
      bridge.newStaticMethodMyClass(a: a, hint: hint);

  Future<String> myFormat({dynamic hint}) => bridge.myFormatMethodMyClass(
        that: this,
      );
}

class NekotonBridgeImpl implements NekotonBridge {
  final NekotonBridgePlatform _platform;
  factory NekotonBridgeImpl(ExternalLibrary dylib) =>
      NekotonBridgeImpl.raw(NekotonBridgePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NekotonBridgeImpl.wasm(FutureOr<WasmModule> module) =>
      NekotonBridgeImpl(module as ExternalLibrary);
  NekotonBridgeImpl.raw(this._platform);
  Future<MnemonicType> resendMnemonic(
      {required MnemonicType mnemonic, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_mnemonic_type(mnemonic);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_resend_mnemonic(port_, arg0),
      parseSuccessData: _wire2api_mnemonic_type,
      constMeta: kResendMnemonicConstMeta,
      argValues: [mnemonic],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kResendMnemonicConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "resend_mnemonic",
        argNames: ["mnemonic"],
      );

  Future<GeneratedKeyG> ntGenerateKey(
      {required MnemonicType accountType, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_mnemonic_type(accountType);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_nt_generate_key(port_, arg0),
      parseSuccessData: _wire2api_generated_key_g,
      constMeta: kNtGenerateKeyConstMeta,
      argValues: [accountType],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kNtGenerateKeyConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "nt_generate_key",
        argNames: ["accountType"],
      );

  Future<List<String>> ntGetHints({required String input, dynamic hint}) {
    var arg0 = _platform.api2wire_String(input);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_nt_get_hints(port_, arg0),
      parseSuccessData: _wire2api_StringList,
      constMeta: kNtGetHintsConstMeta,
      argValues: [input],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kNtGetHintsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "nt_get_hints",
        argNames: ["input"],
      );

  Future<String> ntDeriveFromPhrase(
      {required String phrase,
      required MnemonicType mnemonicType,
      dynamic hint}) {
    var arg0 = _platform.api2wire_String(phrase);
    var arg1 = _platform.api2wire_box_autoadd_mnemonic_type(mnemonicType);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_nt_derive_from_phrase(port_, arg0, arg1),
      parseSuccessData: _wire2api_String,
      constMeta: kNtDeriveFromPhraseConstMeta,
      argValues: [phrase, mnemonicType],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kNtDeriveFromPhraseConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "nt_derive_from_phrase",
        argNames: ["phrase", "mnemonicType"],
      );

  Future<void> initLogger(
      {required LogLevel level, required bool mobileLogger, dynamic hint}) {
    var arg0 = api2wire_log_level(level);
    var arg1 = mobileLogger;
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_init_logger(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kInitLoggerConstMeta,
      argValues: [level, mobileLogger],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kInitLoggerConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "init_logger",
        argNames: ["level", "mobileLogger"],
      );

  Stream<LogEntry> createLogStream({dynamic hint}) {
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_create_log_stream(port_),
      parseSuccessData: _wire2api_log_entry,
      constMeta: kCreateLogStreamConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCreateLogStreamConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "create_log_stream",
        argNames: [],
      );

  Stream<DartCallStubRegistred> initCaller({dynamic hint}) {
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_init_caller(port_),
      parseSuccessData: _wire2api_dart_call_stub_registred,
      constMeta: kInitCallerConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kInitCallerConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "init_caller",
        argNames: [],
      );

  Future<void> callSendResult(
      {required String id, required DynamicValue value, dynamic hint}) {
    var arg0 = _platform.api2wire_String(id);
    var arg1 = _platform.api2wire_box_autoadd_dynamic_value(value);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_call_send_result(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kCallSendResultConstMeta,
      argValues: [id, value],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCallSendResultConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "call_send_result",
        argNames: ["id", "value"],
      );

  Future<void> simpleLog({required String string, dynamic hint}) {
    var arg0 = _platform.api2wire_String(string);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_simple_log(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kSimpleLogConstMeta,
      argValues: [string],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSimpleLogConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "simple_log",
        argNames: ["string"],
      );

  Future<void> simplePanic({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_simple_panic(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kSimplePanicConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSimplePanicConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "simple_panic",
        argNames: [],
      );

  int simpleAdderSync({required int a, required int b, dynamic hint}) {
    var arg0 = api2wire_i32(a);
    var arg1 = api2wire_i32(b);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_simple_adder_sync(arg0, arg1),
      parseSuccessData: _wire2api_i32,
      constMeta: kSimpleAdderSyncConstMeta,
      argValues: [a, b],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSimpleAdderSyncConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "simple_adder_sync",
        argNames: ["a", "b"],
      );

  Future<int> simpleAdder({required int a, required int b, dynamic hint}) {
    var arg0 = api2wire_i32(a);
    var arg1 = api2wire_i32(b);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_simple_adder(port_, arg0, arg1),
      parseSuccessData: _wire2api_i32,
      constMeta: kSimpleAdderConstMeta,
      argValues: [a, b],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSimpleAdderConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "simple_adder",
        argNames: ["a", "b"],
      );

  Future<DynamicValue> stubDv({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_stub_dv(port_),
      parseSuccessData: _wire2api_dynamic_value,
      constMeta: kStubDvConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStubDvConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "stub_dv",
        argNames: [],
      );

  Future<DartCallStub> stubDcs({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_stub_dcs(port_),
      parseSuccessData: _wire2api_dart_call_stub,
      constMeta: kStubDcsConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStubDcsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "stub_dcs",
        argNames: [],
      );

  Future<void> simpleCallDart({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_simple_call_dart(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kSimpleCallDartConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSimpleCallDartConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "simple_call_dart",
        argNames: [],
      );

  Future<void> stubCallDart({required DartCallStub stub, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_dart_call_stub(stub);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_stub_call_dart(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kStubCallDartConstMeta,
      argValues: [stub],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStubCallDartConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "stub_call_dart",
        argNames: ["stub"],
      );

  Future<void> simpleCallFunc0({required bool needResult, dynamic hint}) {
    var arg0 = needResult;
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_simple_call_func0(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kSimpleCallFunc0ConstMeta,
      argValues: [needResult],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSimpleCallFunc0ConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "simple_call_func0",
        argNames: ["needResult"],
      );

  Future<void> simpleCallFunc1({required bool needResult, dynamic hint}) {
    var arg0 = needResult;
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_simple_call_func1(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kSimpleCallFunc1ConstMeta,
      argValues: [needResult],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSimpleCallFunc1ConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "simple_call_func1",
        argNames: ["needResult"],
      );

  Future<void> simpleCallFunc2({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_simple_call_func2(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kSimpleCallFunc2ConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSimpleCallFunc2ConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "simple_call_func2",
        argNames: [],
      );

  Future<MyClass> newStaticMethodMyClass({required int a, dynamic hint}) {
    var arg0 = api2wire_i32(a);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_new__static_method__MyClass(port_, arg0),
      parseSuccessData: (d) => _wire2api_my_class(d),
      constMeta: kNewStaticMethodMyClassConstMeta,
      argValues: [a],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kNewStaticMethodMyClassConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "new__static_method__MyClass",
        argNames: ["a"],
      );

  Future<String> myFormatMethodMyClass({required MyClass that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_my_class(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_my_format__method__MyClass(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kMyFormatMethodMyClassConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMyFormatMethodMyClassConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "my_format__method__MyClass",
        argNames: ["that"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  List<String> _wire2api_StringList(dynamic raw) {
    return (raw as List<dynamic>).cast<String>();
  }

  DynamicValue _wire2api_box_autoadd_dynamic_value(dynamic raw) {
    return _wire2api_dynamic_value(raw);
  }

  DartCallStub _wire2api_dart_call_stub(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DartCallStub(
      fnName: _wire2api_String(arr[0]),
      args: _wire2api_list_dynamic_value(arr[1]),
      namedArgs: _wire2api_list_dynamic_named_value(arr[2]),
    );
  }

  DartCallStubRegistred _wire2api_dart_call_stub_registred(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DartCallStubRegistred(
      id: _wire2api_opt_String(arr[0]),
      stub: _wire2api_dart_call_stub(arr[1]),
    );
  }

  DynamicNamedValue _wire2api_dynamic_named_value(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DynamicNamedValue(
      name: _wire2api_String(arr[0]),
      value: _wire2api_opt_box_autoadd_dynamic_value(arr[1]),
    );
  }

  DynamicValue _wire2api_dynamic_value(dynamic raw) {
    switch (raw[0]) {
      case 0:
        return DynamicValue_U32(
          _wire2api_u32(raw[1]),
        );
      case 1:
        return DynamicValue_I32(
          _wire2api_i32(raw[1]),
        );
      case 2:
        return DynamicValue_U64(
          _wire2api_u64(raw[1]),
        );
      case 3:
        return DynamicValue_I64(
          _wire2api_i64(raw[1]),
        );
      case 4:
        return DynamicValue_F32(
          _wire2api_f32(raw[1]),
        );
      case 5:
        return DynamicValue_F64(
          _wire2api_f64(raw[1]),
        );
      case 6:
        return DynamicValue_String(
          _wire2api_String(raw[1]),
        );
      case 7:
        return DynamicValue_MegaStruct(
          _wire2api_String(raw[1]),
        );
      case 8:
        return DynamicValue_None();
      default:
        throw Exception("unreachable");
    }
  }

  double _wire2api_f32(dynamic raw) {
    return raw as double;
  }

  double _wire2api_f64(dynamic raw) {
    return raw as double;
  }

  GeneratedKeyG _wire2api_generated_key_g(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GeneratedKeyG(
      words: _wire2api_StringList(arr[0]),
      accountType: _wire2api_mnemonic_type(arr[1]),
    );
  }

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }

  int _wire2api_i64(dynamic raw) {
    return castInt(raw);
  }

  List<DynamicNamedValue> _wire2api_list_dynamic_named_value(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_dynamic_named_value).toList();
  }

  List<DynamicValue> _wire2api_list_dynamic_value(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_dynamic_value).toList();
  }

  LogEntry _wire2api_log_entry(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LogEntry(
      timeMillis: _wire2api_i64(arr[0]),
      level: _wire2api_log_level(arr[1]),
      tag: _wire2api_String(arr[2]),
      msg: _wire2api_String(arr[3]),
    );
  }

  LogLevel _wire2api_log_level(dynamic raw) {
    return LogLevel.values[raw];
  }

  MnemonicType _wire2api_mnemonic_type(dynamic raw) {
    switch (raw[0]) {
      case 0:
        return MnemonicType_Legacy();
      case 1:
        return MnemonicType_Labs(
          _wire2api_u16(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  MyClass _wire2api_my_class(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return MyClass(
      bridge: this,
      val: _wire2api_i32(arr[0]),
    );
  }

  String? _wire2api_opt_String(dynamic raw) {
    return raw == null ? null : _wire2api_String(raw);
  }

  DynamicValue? _wire2api_opt_box_autoadd_dynamic_value(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_dynamic_value(raw);
  }

  int _wire2api_u16(dynamic raw) {
    return raw as int;
  }

  int _wire2api_u32(dynamic raw) {
    return raw as int;
  }

  int _wire2api_u64(dynamic raw) {
    return castInt(raw);
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
bool api2wire_bool(bool raw) {
  return raw;
}

@protected
double api2wire_f32(double raw) {
  return raw;
}

@protected
double api2wire_f64(double raw) {
  return raw;
}

@protected
int api2wire_i32(int raw) {
  return raw;
}

@protected
int api2wire_log_level(LogLevel raw) {
  return api2wire_i32(raw.index);
}

@protected
int api2wire_u16(int raw) {
  return raw;
}

@protected
int api2wire_u32(int raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
