// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (String) -> DartFnFuture < Option < String > > + Send + Sync >>>
abstract class ArcFnStringDartFnFutureOptionString
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (String) -> DartFnFuture < () > + Send + Sync >>>
abstract class ArcFnStringDartFnFuture implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (String) -> DartFnFuture < String > + Send + Sync >>>
abstract class ArcFnStringDartFnFutureString implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (String , String) -> DartFnFuture < () > + Send + Sync >>>
abstract class ArcFnStringStringDartFnFuture implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (Vec < u8 >) -> DartFnFuture < Vec < u8 > > + Send + Sync >>>
abstract class ArcFnVecU8DartFnFutureVecU8 implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (u16) -> DartFnFuture < Vec < u8 > > + Send + Sync >>>
abstract class ArcFnU16DartFnFutureVecU8 implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (u16 , Option < i32 > , Vec < u8 >) -> DartFnFuture < Vec < u8 > > + Send + Sync >>>
abstract class ArcFnU16OptionI32VecU8DartFnFutureVecU8
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (u16 , u16 , Option < i32 > , Vec < u8 > , String) -> DartFnFuture < Vec < u8 > > + Send + Sync >>>
abstract class ArcFnU16U16OptionI32VecU8StringDartFnFutureVecU8
    implements RustOpaqueInterface {}
