targets:
  $default:
    sources:
      - lib/**
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
    builders:
      reflectable:
        generate_for:
          - lib/example_related/caller_wrapper.dart
          - lib/example_related/caller_test_class_wrapper.dart
        options:
          formatted: true
