targets:
  $default:
    sources:
      - lib/**
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
    builders:
      json_serializable:
          options:
            explicit_to_json: true
      reflectable:
        generate_for:
          - lib/example_related/caller_wrapper.dart
          - lib/example_related/caller_test_class_wrapper.dart
          - lib/nekoton/external/gql_connection.dart
          - lib/nekoton/external/proto_connection.dart
          - lib/nekoton/external/jrpc_connection.dart
          - lib/nekoton/external/ledger_connection.dart
          - lib/nekoton/external/storage.dart
          - lib/nekoton/core/ton_wallet/ton_wallet.dart
          - lib/nekoton/core/token_wallet/token_wallet.dart
          - lib/nekoton/core/generic_contract/generic_contract.dart
        options:
          formatted: true
