name: Create Release(s)

on:
  workflow_dispatch:
    inputs:
      version_parameters:
        description: 'Parameters to pass to "melos version"'
        required: true
        default: " "
        type: choice
        options:
          - "--"
          - "--prerelease"
          - "--graduate"

env:
  CARGO_INCREMENTAL: "1"

jobs:
  create_release:
    uses: broxus/flutter_templates/.github/workflows/version.yaml@main
    with:
      version_parameters: ${{ inputs.version_parameters }}
      user_name: 'nesquikm'
      user_email: 'drapolyuk@gmail.com'
      push_tags: true
    secrets:
      token: ${{ secrets.BOT_ACCESS_TOKEN }}
