name: Create Release(s)

on:
  workflow_dispatch:
    inputs:
      version_parameters:
        description: 'Parameters to pass to "melos version"'
        required: true
        default: " "
        type: choice
        options:
          - "--"
          - "--prerelease"
          - "--graduate"

env:
  CARGO_INCREMENTAL: "1"

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup git
        run: |
          git config user.name "Odrin"
          git config user.email "odrin666@gmail.com"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - uses: bluefireteam/melos-action@v3

      - name: Create the new version(s)
        run: melos version -a --yes ${{ inputs.version_parameters }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          commit-message: "chore: version bump"
          committer: nesquikm <drapolyuk@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: version-bump
          delete-branch: true
          title: "chore: version bump"
          body: |
            ## Description

            This is an automated PR to bump the version of the package.

            ## Type of Change

            - [x] 🗑️ Chore

          labels: |
            version_bump
            automated_pr
          draft: false

      - name: Push modified tags
        run: git push --tags
